### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by jrosebaugh** [DylanDmitri/spamalot#27]
```
+[2018-10-31 16:32:56,904] ERROR in app: Exception on / [POST]
+Traceback (most recent call last):
+  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
+    response = self.full_dispatch_request()
+  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
+    rv = self.handle_user_exception(e)
+  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
+    reraise(exc_type, exc_value, tb)
+  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
+    raise value
+  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
+    rv = self.dispatch_request()
+  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
+    return self.view_functions[rule.endpoint](**req.view_args)
+  File "spam.py", line 330, in form
+    return self.process(request.form)
+TypeError: 'NotImplementedType' object is not callable
+127.0.0.1 - - [31/Oct/2018 16:32:57] "POST / HTTP/1.0" 500 -
+127.0.0.1 - - [31/Oct/2018 16:32:57] "POST /alexa HTTP/1.0" 404 -
+[2018-10-31 16:32:57,353] ERROR in app: Exception on / [POST]
+Traceback (most recent call last):
+  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
+    response = self.full_dispatch_request()
+  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
+    rv = self.handle_user_exception(e)
+  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
+    reraise(exc_type, exc_value, tb)
+  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
+    raise value
+  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
+    rv = self.dispatch_request()
+  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
+    return self.view_functions[rule.endpoint](**req.view_args)
+  File "spam.py", line 330, in form
+    return self.process(request.form)
+TypeError: 'NotImplementedType' object is not callable
```

- James Onnen

**Comment by Quenty** [comment]
See #25
